POST http://localhost:3333/videos 
Content-type: application/json

{
    "Title": "Video 2",
    "Description": "This is the number 1 video",
    "Lenght": 180
}

###
GET  http://localhost:3333/videos 

###
GET  http://localhost:3333/videos/search?movie=Video 1 

###
PUT http://localhost:3333/videos/23ba7d80-3dbe-4902-b488-3cdb97fe2f8e
Content-type: application/json

{
    "Title": "Novo vídeo 1",
    "Description": "This is the new number 1 video!",
    "Length": 90
}

###
DELETE http://localhost:3333/videos/0c326564-3e51-4ff2-9db9-8b3ff6636052