POST http://localhost:3333/videos 
Content-type: application/json

{
    "Title": "Video 1",
    "Description": "This is the number 1 video",
    "Length": 180
}

###
GET  http://localhost:3333/videos 

###
GET  http://localhost:3333/videos/search?movie=Vídeo  

###
PUT http://localhost:3333/videos/7803412d-555e-4675-9099-accf376bc3d6
Content-type: application/json

{
    "Title": "Novo vídeo 1133",
    "Description": "This is the new number 1 video!",
    "Length": 90
}

###
DELETE http://localhost:3333/videos/dcdcd25e-5e94-4cc9-9327-26bcd6cd7e38