POST https://first-steps-node.onrender.com/videos 
Content-type: application/json

{
    "Title": "Video 2",
    "Description": "This is the number 2 video",
    "Length": 180
}

###
GET  https://first-steps-node.onrender.com/videos 

###
GET  https://first-steps-node.onrender.com/videos/search?movie=Vídeo  

###
PUT https://first-steps-node.onrender.com/videos/7803412d-555e-4675-9099-accf376bc3d6
Content-type: application/json

{
    "Title": "Novo vídeo 1133",
    "Description": "This is the new number 1 video!",
    "Length": 90
}

###
DELETE https://first-steps-node.onrender.com/videos/dcdcd25e-5e94-4cc9-9327-26bcd6cd7e38